server:
  address: 127.0.0.1
  port: 9999
spring:
  application:
    name: cloud-payment-service
  datasource:
    url: jdbc:mysql://localhost:3308/springclouddemo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    username: ying
    password: newman123

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.cloud.entities

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#    eureka-server-port: 7001