server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eurek
spring:
  application:
    name: cloud-consumer-order
  datasource:
    url: jdbc:mysql://localhost:3308/springclouddemo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    username: ying
    password: newman123

logging:
  level:
#    feign以哪一个日志级别监听哪一个接口
    org.example.cloud.service.PaymentFeignService: debug
feign:
  hystrix:
    enabled: true
