server:
  port: 9002
spring:
  application:
    name: alibaba-consumer
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"

